title: "Clyde Lhui's Personal Site"
author:
  name: Clyde Lhui
  email: "clydelhui@gmail.com"
#header_pages: 
#- about.md
description: > # this means to ignore newlines until "show_excerpts:"
  A little Physics, Math and Computer Science
minima: 
  skin: dark
theme: minima
